"""opportunities: opportunities, lines, stage history and the activity link

Revision ID: 0006_opportunities
Revises: 0005_product_catalogue
Create Date: 2026-08-28 18:10:35+00:00

Reviewed by hand after autogenerate:
- both enums dropped on downgrade
- checks: closing fields per status, tender fields only on tenders, at-risk flag/since pair
- partial indexes for tender deadlines and at-risk rows; board index (pipeline, stage, status)
- named FK for activities.opportunity_id (ON DELETE SET NULL)
- crm_app grants on the new tables (guarded: only when the role exists)
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0006_opportunities"
down_revision: str | None = "0005_product_catalogue"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


GRANT_APP_ROLE = """
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'crm_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE
        ON opportunities, opportunity_lines, opportunity_stage_history TO crm_app;
    END IF;
END
$$;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opportunities",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_id", sa.Uuid(), nullable=False),
        sa.Column("stage_id", sa.Uuid(), nullable=False),
        sa.Column("division_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "won", "lost", name="opportunities_status_enum"),
            nullable=False,
        ),
        sa.Column("estimated_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("expected_close_date", sa.Date(), nullable=False),
        sa.Column("won_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("won_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lost_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("loss_reason_id", sa.Uuid(), nullable=True),
        sa.Column("competitor_brand_id", sa.Uuid(), nullable=True),
        sa.Column("loss_note", sa.Text(), nullable=True),
        sa.Column("is_tender", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("tender_reference", sa.Text(), nullable=True),
        sa.Column("tender_deadline", sa.Date(), nullable=True),
        sa.Column("estimated_award_date", sa.Date(), nullable=True),
        sa.Column("is_at_risk", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("at_risk_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "at_risk_source",
            sa.Enum("manual", "automatic", name="opportunities_at_risk_source_enum"),
            nullable=True,
        ),
        sa.Column("stage_entered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "status <> 'lost' OR (loss_reason_id IS NOT NULL AND lost_at IS NOT NULL)",
            name="ck_opportunities_lost_requires_reason",
        ),
        sa.CheckConstraint(
            "status <> 'won' OR won_at IS NOT NULL", name="ck_opportunities_won_requires_won_at"
        ),
        sa.CheckConstraint("amount >= 0", name="ck_opportunities_amount"),
        sa.CheckConstraint("estimated_amount >= 0", name="ck_opportunities_estimated_amount"),
        sa.CheckConstraint(
            "is_at_risk = (at_risk_since IS NOT NULL)", name="ck_opportunities_at_risk_since"
        ),
        sa.CheckConstraint(
            "is_tender OR (tender_reference IS NULL AND tender_deadline IS NULL AND estimated_award_date IS NULL)",
            name="ck_opportunities_tender_fields",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["competitor_brand_id"], ["brands.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["division_id"], ["divisions.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["loss_reason_id"], ["loss_reasons.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pipeline_id"], ["pipelines.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["stage_id"], ["pipeline_stages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunities_account_status", "opportunities", ["account_id", "status"], unique=False
    )
    op.create_index(
        "ix_opportunities_at_risk",
        "opportunities",
        ["is_at_risk"],
        unique=False,
        postgresql_where="is_at_risk",
    )
    op.create_index(
        "ix_opportunities_board",
        "opportunities",
        ["pipeline_id", "stage_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_close_date",
        "opportunities",
        ["status", "expected_close_date"],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_owner_status", "opportunities", ["owner_id", "status"], unique=False
    )
    op.create_index(
        "ix_opportunities_tender_deadline",
        "opportunities",
        ["tender_deadline"],
        unique=False,
        postgresql_where="is_tender AND status = 'open'",
    )
    op.create_table(
        "opportunity_lines",
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name="ck_opportunity_lines_quantity"),
        sa.CheckConstraint("unit_price >= 0", name="ck_opportunity_lines_unit_price"),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id", "product_id", name="uq_opportunity_lines_product"),
    )
    op.create_index(
        "ix_opportunity_lines_opportunity_id", "opportunity_lines", ["opportunity_id"], unique=False
    )
    op.create_table(
        "opportunity_stage_history",
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("from_stage_id", sa.Uuid(), nullable=True),
        sa.Column("to_stage_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("seconds_in_previous_stage", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["from_stage_id"], ["pipeline_stages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_stage_id"], ["pipeline_stages.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_opportunity_stage_history_timeline",
        "opportunity_stage_history",
        ["opportunity_id", "occurred_at"],
        unique=False,
    )
    op.add_column("activities", sa.Column("opportunity_id", sa.Uuid(), nullable=True))
    op.create_index("ix_activities_opportunity_id", "activities", ["opportunity_id"], unique=False)
    op.create_foreign_key(
        "fk_activities_opportunity_id",
        "activities",
        "opportunities",
        ["opportunity_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.execute(GRANT_APP_ROLE)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_activities_opportunity_id", "activities", type_="foreignkey")
    op.drop_index("ix_activities_opportunity_id", table_name="activities")
    op.drop_column("activities", "opportunity_id")
    op.drop_index("ix_opportunity_stage_history_timeline", table_name="opportunity_stage_history")
    op.drop_table("opportunity_stage_history")
    op.drop_index("ix_opportunity_lines_opportunity_id", table_name="opportunity_lines")
    op.drop_table("opportunity_lines")
    op.drop_index(
        "ix_opportunities_tender_deadline",
        table_name="opportunities",
        postgresql_where="is_tender AND status = 'open'",
    )
    op.drop_index("ix_opportunities_owner_status", table_name="opportunities")
    op.drop_index("ix_opportunities_close_date", table_name="opportunities")
    op.drop_index("ix_opportunities_board", table_name="opportunities")
    op.drop_index(
        "ix_opportunities_at_risk", table_name="opportunities", postgresql_where="is_at_risk"
    )
    op.drop_index("ix_opportunities_account_status", table_name="opportunities")
    op.drop_table("opportunities")
    for enum_name in ("opportunities_status_enum", "opportunities_at_risk_source_enum"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
