/** Stable machine-readable error codes emitted by the backend (design D6). */
export const ERROR_CODES = [
  'invalid_credentials',
  'account_locked',
  'rate_limited',
  'unauthenticated',
  'forbidden',
  'not_found',
  'conflict',
  'precondition_required',
  'validation_error',
  'invalid_sort_field',
  'email_already_exists',
  'unknown_reference',
  'cannot_demote_self',
  'invalid_current_password',
  'password_too_short',
  'invalid_email',
  'province_already_assigned',
  'invalid_province',
  'territory_in_use',
  'territory_name_already_exists',
  'brand_name_already_exists',
  'loss_reason_name_already_exists',
  'pipeline_name_already_exists',
  'stage_order_invalid',
  'stage_probability_invalid',
  'stage_flag_immutable',
  'last_active_stage',
  'tax_id_invalid',
  'tax_id_already_exists',
  'postal_code_invalid',
  'phone_invalid',
  'address_label_duplicated',
  'too_many_addresses',
  'assignment_forbidden',
  'owner_not_sales_rep',
  'contact_anonymised',
  'consent_incomplete',
  'preferred_channel_missing_value',
  'job_title_name_already_exists',
  'invalid_activity_transition',
  'activity_locked',
  'contact_not_in_account',
  'note_cannot_be_planned',
  'cancel_reason_required',
  'next_action_in_past',
  'duration_invalid',
  'product_sku_exists',
  'product_sku_locked',
  'product_family_exists',
  'price_invalid',
  'brand_not_found',
  'family_not_found',
  'pipeline_required',
  'stage_not_in_pipeline',
  'invalid_opportunity_transition',
  'opportunity_closed',
  'loss_reason_requires_brand',
  'loss_reason_requires_note',
  'opportunity_has_lines',
  'tender_fields_require_tender',
  'at_risk_not_supported',
  'line_product_inactive',
  'line_duplicated',
  'reopen_forbidden',
  'opportunity_not_in_account',
  'quote_not_editable',
  'quote_superseded',
  'quote_action_forbidden',
  'quote_recipients_required',
  'email_retry_not_available',
  'invalid_vat_rate',
  'opportunity_already_closed',
  'internal_error',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export function isKnownErrorCode(code: string): code is ErrorCode {
  return (ERROR_CODES as readonly string[]).includes(code);
}
